image: "dmatrix.azurecr.io/test-mlteam:v3"

stages:
  - test
  - deploy

cache:
  key: $CI_PIPELINE_ID
  paths:
    - .venv

test:
  cache: []
  before_script:
    - export PYENV_ROOT=$HOME/.pyenv
    - export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - mc alias set minio http://10.10.6.184:9000 rootuser rootpass123
    - mc cp minio/creds/gitlab_runner_ed25519 ~/.ssh/id_rsa
    - mc cp minio/creds/git.d-matrix.ai.crt /usr/local/share/ca-certificates
    - update-ca-certificates
    - chmod 400 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install .
    - pip install ipdb
    - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python build-dmir-proto
    - pytest -vv ./tests/*.py

triger-mlreferences:
  variables:
    UPSTREAM_MLTOOLS_BRANCH: $CI_COMMIT_REF_NAME
  stage: deploy
  trigger:
    project: ml-team/mlreferences
    strategy: depend
