image: "dmatrix.azurecr.io/test-mlteam:v5"

stages:
  - test
  - deploy

test:
  cache: []
  before_script:
    - export PYENV_ROOT=$HOME/.pyenv
    - export PATH=$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
    - mc --insecure alias set minio https://minio.minio:443 minio minio123
    - mc --insecure cp minio/creds/gitlab_runner_ed25519 ~/.ssh/id_rsa
    - mc --insecure cp minio/creds/git.d-matrix.ai.crt /usr/local/share/ca-certificates
    - update-ca-certificates
    - chmod 400 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  script:
    - python -m venv .venv
    - source .venv/bin/activate
    - pip install .
    - pip install ipdb
    - pip install 'git+ssh://git@git.d-matrix.ai/software/software.git#subdirectory=tools/simulators/numerics'
    - pytest -vv ./tests/*.py

triger-mlreferences:
  variables:
    UPSTREAM_MLTOOLS_BRANCH: $CI_COMMIT_REF_NAME
  stage: deploy
  trigger:
    project: ml-team/mlreferences
    strategy: depend
