conv1:
  accum_format: SAME
  approximation_function: NONE
  bias_format: SAME
  input_format: BFP[8|8]{64,1}(SN)
  instance: Conv2d
  output_format: FP[1|5|10,15](FN)
  weight_format: BFP[8|8]{64,1}(SN)
  weight_sparseness: DENSE
conv2:
  accum_format: SAME
  approximation_function: NONE
  bias_format: SAME
  input_format: BFP[8|8]{64,1}(SN)
  instance: Conv2d
  output_format: FP[1|5|10,15](FN)
  weight_format: BFP[8|8]{64,1}(SN)
  weight_sparseness: DENSE
fc1:
  accum_format: SAME
  approximation_function: NONE
  bias_format: SAME
  input_format: BFP[8|8]{64,-1}(SN)
  instance: Linear
  output_format: FP[1|5|10,15](FN)
  weight_format: BFP[8|8]{64,-1}(SN)
  weight_sparseness: DENSE
fc2:
  accum_format: SAME
  approximation_function: NONE
  bias_format: SAME
  input_format: BFP[8|8]{64,-1}(SN)
  instance: Linear
  output_format: FP[1|5|10,15](FN)
  weight_format: BFP[8|8]{64,-1}(SN)
  weight_sparseness: DENSE
fc3:
  accum_format: SAME
  approximation_function: NONE
  bias_format: SAME
  input_format: BFP[8|8]{64,-1}(SN)
  instance: Linear
  output_format: FP[1|5|10,15](FN)
  weight_format: BFP[8|8]{64,-1}(SN)
  weight_sparseness: DENSE
mp1:
  approximation_function: NONE
  input_format: SAME
  instance: MaxPool2d
  output_format: FP[1|5|10,15](FN)
mp2:
  approximation_function: NONE
  input_format: SAME
  instance: MaxPool2d
  output_format: FP[1|5|10,15](FN)
