model:
  input_format: BFP[8|8]{64,-1}(N)
  output_format: FP[1|5|10]{15}(N)
act_func:
  approximation_function: NONE
  input_format: SAME
  instance: ReLU
  output_format: FP[1|5|10]{15}(N)
input_layer:
  accum_format: SAME
  approximation_function: NONE
  bias_format: SAME
  input_format: BFP[8|8]{64,-1}(N)
  instance: Linear
  output_format: FP[1|5|10]{15}(N)
  weight_format: BFP[8|8]{64,-1}(N)
  weight_sparseness: DENSE
intermediate_layers.0:
  accum_format: SAME
  approximation_function: NONE
  bias_format: SAME
  input_format: BFP[8|8]{64,-1}(N)
  instance: Linear
  output_format: FP[1|5|10]{15}(N)
  weight_format: BFP[8|8]{64,-1}(N)
  weight_sparseness: DENSE
output_layer:
  accum_format: SAME
  approximation_function: NONE
  bias_format: SAME
  input_format: BFP[8|8]{64,-1}(N)
  instance: Linear
  output_format: FP[1|5|10]{15}(N)
  weight_format: BFP[8|8]{64,-1}(N)
  weight_sparseness: DENSE
